const projects = [
  {
    id: 1,
    title: "Beauty Bliss – React E-Commerce Website",
    desc: "Responsive beauty products e-commerce site with product listing, cart, and checkout built with React & Tailwind CSS.",
    image: "/images/Blushora.jpg",
    tech: ["React", "Tailwind CSS", "React Router", "Framer Motion"],
    live: "https://blushora.vercel.app/",
    github: "https://github.com/zaheerahmadz/Blushora",
    featured: true,
  },
  {
    id: 2,
    title: "Industrial & Factory Corporate Website",
    desc: "Professional industrial website designed for engineering and manufacturing businesses.",
    image: "/images/Eng.jpg",
    tech: ["React", "Tailwind", "UI Design"],
    live: "https://nictorys-factory-industrial.vercel.app/",
    github: "https://github.com/zaheerahmadz/Nictorys---Factory-Industrial",
    featured: true,
  },
  {
    id: 3,
    title: "Arsha Business Solutions Platform",
    desc: "Responsive business website with modern UI, optimized performance, and scalable component structure.",
    image: "/images/Arsha.jpg",
    tech: ["React", "Tailwind", "Responsive UI"],
    live: "https://arsha-project-omega.vercel.app/",
    github: "https://github.com/yourusername/arsha-project",
    featured: true,
    url: "https://github.com/zaheerahmadz/arsha-project",
  },

  {
    id: 4,
    title: "Modern Real Estate Landing Page",
    desc: "This is a demo template for property listings and client contact. Fully responsive and mobile-friendly, perfect for showcasing properties online. I can customize it for your business to attract more clients",
    image: "/images/Real.jpeg",
    tech: ["React", "Tailwind", "Responsive"],
    live: "https://html.themewin.com/pixells/quarter-tailwind-preview/quarter/index.html",
    github: "#",
    featured: true,
  },
  {
    id: 5,
    title: "Creative Agency Website",
    desc: "This is demo, responsive agency website showcasing services, team, and portfolio with interactive UI and smooth animations built using React & Tailwind CSS.",
    image: "/images/agency.jpeg",
    tech: ["React", "Tailwind CSS", "Framer Motion", "React Router"],
    live: "https://ethemestudio.com/demo/inc/index.html",
    github: "https://ethemestudio.com/demo/inc/index.html",
    featured: false,
  },
  {
    id: 6,
    title: "Modern Portfolio Website",
    desc: "A sleek, responsive portfolio showcasing projects and skills with smooth animations and modern UI built with React & Tailwind CSS.",
    image: "/images/clint.jpg",
    tech: ["React", "Tailwind CSS", "Framer Motion", "React Router"],
    live: "https://dragoedits.netlify.app/about",
    github: "https://github.com/zaheerahmadz/arsha-project",
    featured: false,
  },
  {
    id: 7,
    title: "Dental Clinic Website",
    desc: "A responsive dental clinic website showcasing services, doctors, appointments, and patient information, built with React & Tailwind CSS.",
    tech: ["React", "Tailwind CSS", "Framer Motion", "React Router"],
    image: "/images/dental.jpeg",
    live: "https://meditics.temptics.com/?storefront=envato-elements",
    github: "https://meditics.temptics.com/?storefront=envato-elements",
    featured: false,
  },
  {
    id: 8,
    title: "Gourmet Restaurant Website",
    desc: "A modern, responsive restaurant website showcasing menu, reservations, and chef specials with interactive UI built using React & Tailwind CSS.",
    tech: ["React", "Tailwind CSS", "Framer Motion", "React Router"],
    image: "/images/resturent.jpg",
    live: "https://gramentheme.com/html/fresheat/?storefront=envato-elements",
    github: "https://gramentheme.com/html/fresheat/?storefront=envato-elements",
    featured: false,
  },
  {
    id: 9,
    title: "School Website",
    desc: "A responsive school website showcasing courses, faculty, events, and student resources, built with React & Tailwind CSS for modern UI and easy navigation.",
    tech: ["React", "Tailwind CSS", "Framer Motion", "React Router"],
    image: "/images/school.jpg",
    live: "https://edumon-nextjs.vercel.app/?storefront=envato-elements",
    github: "https://edumon-nextjs.vercel.app/?storefront=envato-elements",
    featured: false,
  },
];

export default projects;
